### ISSUE TITLE
Not compatible with flutter_tts

### ISSUE THREAD

**Issue by prantto** [csdcorp/speech_to_text#43]
I want to build an app, where you speak a word and flutter_tts speaks the data that was found to the search term in the database. The problem what I found out is, after the speech to text was used once flutter_tts do not speaks anymore:/ 
But this issue only comes to me on the real device (iPhones), in the ios Simulator everything is working fine. Do you have an idea, why that happens?

You can reproduce that issue if you add to your example app 
```
FloatingActionButton(onPressed: () {
                        FlutterTts flutterTts = new FlutterTts();
                        flutterTts.setLanguage("en-US");
                        flutterTts.speak(lastWords);
                      }),
```
this snipped of code. 
I really can't understand why it is working on the Simulator but not on the real device (ios)

**Comment by sowens-csd** [comment]
Good news, they're definitely compatible, I use them together in applications I've built. First question, are you calling `stop` on SpeechToText before trying to use `speak`? Both plugins try to take over the audio and I don't think the two sessions will co-exist. However SpeechToText only holds onto it while there is an active `listen` session going on so you should just need to call `stop`. 

The difference in behaviour between the simulator and the real device is because the sound drivers on a computer are very different, and much more capable, than what is on an actual device.

**Comment by prantto** [comment]
Oh really. That gives me hope. Because I have this problem now for a while and I don't found a work around. I just added a button to your example app. I press the start button, speak for example "hello". Then I press the stop Button. So it is saying in the status not listening and then I press my new speak Button. On the iPhone nothing happens, on the simulator it works fine.
When I press the stop button, I call speech.stop(). Or do I have to stop the SpeechToText on another way?

**Comment by sowens-csd** [comment]
Yes, what you are doing should work. Are you seeing any log output or errors? If you click the speak button before initializing the SpeechToText plugin or starting a listen session does it work? I.e. can you get flutter_tts to speak on the iPhone when there is no interaction with SpeechToText?

**Comment by prantto** [comment]
I only added a default string for `lastwords=hello` . So I expected that tts speaks hello. (worked as I thought). But then I tested again if tts is not working after speechToText was called and it worked. Can't understand why? Just tested it 5 min before on an android device, too. And it didn't worked. I really haven't changed anything else. 
Only have to test why it is not working in my real app. Or maybe it is working there now. I feel really stupid right now.

**Comment by sowens-csd** [comment]
Sounds like this issue is resolved? I'll leave this open for another couple of days and then close if there's no further questions.

**Comment by amjad07** [comment]
hi there, the problem still exists in 2021. 
after speak to text I stop the speak sesstion and want to call the text to speak. it is not working in physical iPhone but on simulators it is working good.
[avas]     AVAudioSession_iOS.mm:1206  Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by sowens-csd** [comment]
I think you're seeing a different issue. This sounds more closely related to #241 that I just committed a fix for that in 5.0.0.
